import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

export default {
    rulesAcademic: [{ type: 'autogenerated', dirName: 'rules/academic' }],
    rulesCommunity: [{ type: 'autogenerated', dirName: 'rules/community' }],
    manualLuogu: [{ type: 'autogenerated', dirName: 'manual/luogu' }],
    manualClass: [{ type: 'autogenerated', dirName: 'manual/class' }],
    ula: [{ type: 'autogenerated', dirName: 'ula' }]
} satisfies SidebarsConfig;
