// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    rulesAcademic: [{ type: 'autogenerated', dirName: 'rules/academic' }],
    rulesCommunity: [{ type: 'autogenerated', dirName: 'rules/community' }],
    manualLuogu: [{ type: 'autogenerated', dirName: 'manual/luogu' }],
    manualClass: [{ type: 'autogenerated', dirName: 'manual/class' }],
    ula: [{ type: 'autogenerated', dirName: 'ula' }],
    main: ['index']
};

module.exports = sidebars;
